### ISSUE TITLE
Adding previews for ODP files

### ISSUE THREAD

**Issue by rjlynch** [DFE-Digital/curriculum-materials#133]
# Adding previews for resources.

Using active storage's preview functionality to generate previews for open
document attachments complicates our deployment by requiring libreoffice
to be installed. It also introduces some overhead when viewing a preview as
libreoffice needs to be spun up.
Instead we suggest generating previews at content consumption time and attach
them along with their corresponding file to a new model `Resource`. This provides the added benefit of allowing suppliers to provide their own preview for a resource.

```
class Activity
  has_many pupil_resources, -> { where type: 'pupil_resource' }, class_name: 'Resource'
  has_many teacher_resources, -> { where type: 'teacher_resource' }, class_name: 'Resource'
  has_one slide_deck, -> { where type: 'slide_deck' }, class_name: 'Resource'
end

class Resource
  belongs_to :activity

  has_one_attached :file
  has_one_attached :preview
end
```

Thoughts?

**Comment by peteryates** [comment]
This sounds sensible to me and offers more flexibility in the future. Definitely prefer STI over polymorphism.
