### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/curriculum-materials#20]
The README hasn't been updated, it should be changed to reflect the project, describe the stack and explain how to get up and running

**Comment by rjlynch** [comment]
We'll want to add instructions for running the docker file. I'll leave them here for the time being as it seems a bit pointless partially updating the readme at the minute.

To run:
cd to the project directory and run

`docker build . -t curriculum_materials:latest`
`docker-compose up`

To stop the app run
`docker-compose down`
