### ISSUE TITLE
Updating the schema to fit with the exemplar lesson content

### ISSUE THREAD

**Issue by rjlynch** [DFE-Digital/curriculum-materials#38]
Raising this to discus fitting the exemplar lesson content into the schema / extensions to the schema we need to make.

Looks like [Beth did some work on this](https://dfedigital.atlassian.net/wiki/spaces/CMB/pages/1309573178/Lesson+Plan+with+exemplar+content+-+content+design+edits)

Here's an erd diagram from my spike branch which seems to import the content:

[erd.pdf](https://github.com/DFE-Digital/curriculum-materials/files/4154624/erd.pdf)

**Comment by peteryates** [comment]
This looks great, `LessonPart`, `Activity` and `Resource` _feel_ like they make sense when it comes to forming a lesson.

**Comment by rjlynch** [comment]
I'm closing this as I think we're there now as far as representing the exemplar content
