### ISSUE TITLE
Unique index on activity choices

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/curriculum-materials#59]
We currently have a unique index on `activity choices` across the columns `activity_id`, `teacher_id`, `lesson_part_id`.

This prevents a teacher from choosing the _same activity_ twice. I think the uniqueness should be on just `teacher_id` and `lesson_part_id`, limiting them to a single choice per lesson part.

**Comment by rjlynch** [comment]
yeah that makes sense, do you want to fix it as part of #60 ? Or do you want me to shoot up a separate pr for that?

**Comment by peteryates** [comment]
It's not impeding #60 so I think a separate pr makes most sense
