### ISSUE TITLE
Cleaning up the seeds

### ISSUE THREAD

**Issue by rjlynch** [DFE-Digital/curriculum-materials#62]
We want to keep the seed file manageable as we'll be using this to load data into our staging environment and ideally have it so it's editable by none developers.
Opening this issue for discussing the best way to do that.

- [x] Get ticket in sprint to fix seeds

**Comment by rjlynch** [comment]
I think we could use some of @kylewelsby 's file based pr's code / file structure and use that to store the content in directories and build the db models in the seed file.

Another idea is to store the content in directories and have a script to push the data into the db using the api - this would ensure we keep the api up to date as we go.

We should make sure to get a ticket for cleaning the seeds up in the next sprint.

**Comment by peteryates** [comment]
I was just heading here to raise the same ticket! Totally agree, I've added even more debt to them in #60 

I'm easy on _how_ it's done, a directory based approach sounds good for this but there'll be a _lot_ of small files.
